### ISSUE TITLE
Start bidirectional dshrot can only recognize two motors

### ISSUE THREAD

**Issue by Cl-arctos** [mathiasvr/bluejay#21]
**Describe the bug**
Start bidirectional dshrot can only recognize two motors(only motor 1,2），Turn off the normal recognition of 4 motors

**Expected behavior**
A description of what you expected to happen.

**Configuration:**
 - Bluejay version:0.11-96k/48k   0.10-96k/48k
 - ESC variant: G-h-30
 - Bidirectional DShot: ON
 - FC firmware: [e.g. Betaflight 4.3.0]

**Comment by mathiasvr** [comment]
Could this be related to this issue https://github.com/mathiasvr/bluejay-configurator/issues/12?

**Comment by mathiasvr** [comment]
@Cl-arctos Are you using iFlight Beast H7?

**Comment by mathiasvr** [comment]
Closing as stale.
