### ISSUE TITLE
ESC not showing flashed version 0.12.1 or 0.12.2 ?

### ISSUE THREAD

**Issue by Zuldan** [mathiasvr/bluejay#25]
I've just flashed my ESC from 0.12.1 to 0.12.2 but the Configurator is still showing 0.12. How do I know if I have 0.12.1 or 0.12.2 installed?

**Configuration:**
 - Bluejay version: 0.12.2
 - ESC variant: A-H-25

<img width="305" alt="Version" src="https://user-images.githubusercontent.com/12680150/117251035-731c8900-ae87-11eb-9df6-40a9e067fbb6.PNG">

**Comment by mathiasvr** [comment]
Sorry about that, I chose to reuse the 0.12 version number but should probably just have made it 0.13.

If you can reverse the motor direction you are not running 0.12.1.

**Comment by Zuldan** [comment]
Ok no prob. I'll install 0.13
