### ISSUE TITLE
ESC lost after upgrade

### ISSUE THREAD

**Issue by AndreaCCIE** [mathiasvr/bluejay#27]
**Describe the bug**
I lost one ESC after the upgrade from 0.11 to 0.13

![Screenshot 2021-05-20 at 16 08 53](https://user-images.githubusercontent.com/48698293/119003587-beee2880-b985-11eb-8170-cbc6198eabe9.png)

**Expected behavior**
All 4 sec should be in the list

**Configuration:**
 - Bluejay version: 1.3.6
 - ESC variant: S-H-50
 - Bidirectional DShot: 300
 - FC firmware: Betaflight 4.3

**Comment by mathiasvr** [comment]
Try waiting some time before pressing read setup, does the ESC still not show up?
Could you save debug logs and post them here?

**Comment by AndreaCCIE** [comment]
No difference. I flew a pack (it's a tiny whoop), went for the upgrade and got the problem.

[Uploading Log.txt…]()

**Comment by mathiasvr** [comment]
Looks like it failed to flash, but seems it should still show up. Can you try if esc-configurator.com is able to read it?

**Comment by AndreaCCIE** [comment]
Yes, it does see the 4 escs but it doesn't spin (number 3)

![Screenshot 2021-05-20 at 19 18 42](https://user-images.githubusercontent.com/48698293/119029161-3466f280-b9a0-11eb-816a-b165abd465b0.png)

**Comment by AndreaCCIE** [comment]
Actually, it doesn't show number 3

![Screenshot 2021-05-20 at 20 41 38](https://user-images.githubusercontent.com/48698293/119039149-d4764900-b9ab-11eb-9754-002966815773.png)

**Comment by mathiasvr** [comment]
Okay, looks like you have to flash using C2 interface to recover the esc unfortunately. This is not straightforward and you will need an Arduino or similar.

I'm not sure why this happened, but maybe there is some state bug in blheli/bluejay configurator - seems to be quite rare though.

**Comment by mathiasvr** [comment]
There was a bug in blheli/bluejay configurator that could brick the ESC if the `Flash` button was pressed more than once.
I have fixed it in the latest version. Not sure if this is what happened in your case, but I hope we can avoid these problems in the future.
