### ISSUE TITLE
iFlight Beast F7 45A AIO - No RPM Telemetry when motors are not spinning

### ISSUE THREAD

**Issue by c3r63ru5** [mathiasvr/bluejay#42]
**Describe the bug**

Flashed 0.15 48kHz onto a iFlight F7 Beast AIO and checked RPM telemetry in BF.
With BLheli_M all looks normal, with BlueJay Error shows 100% until motors start spinning.
When motors start spinning, error goes down to 0%.

**Expected behavior**

Even with motors not spinning, I would expect 0% telemetry errors.

**Configuration:**

 - Bluejay version: 0.15
 - ESC variant: G_H_30
 - PWM frequency: 48
 - DShot bitrate: 600
 - Bidirectional DShot: On
 - FC firmware: Betaflight 4.2.12

**Comment by mathiasvr** [comment]
I have released v0.16 as a small fix for this.
