### ISSUE TITLE
brake on stop at zero throttle

### ISSUE THREAD

**Issue by kasatka60** [mathiasvr/bluejay#46]
is it possible to implement a brake on stop at zero throttle on airplanes?

**Comment by kasatka60** [comment]
so that the brake only works at zero throttle.
when the gas is reduced, the brake does not engage.

**Comment by mathiasvr** [comment]
Okay, so basically having 'max braking strength' at zero (no active braking / damped light), but at zero throttle it should do full braking? This is similar to what 'brake on stop' does but it has a delay before it kicks in and will disarm the ESC before.

Have you tried 'braking strength' at 0 with 'brake on stop' enabled? Is this close to what you want?

**Comment by kasatka60** [comment]
I'll try
