### ISSUE TITLE
Motors spin up when motor slider goes from 1000-1500, then stops at 1501 and spins up from 1501-2000

### ISSUE THREAD

**Issue by SquidDerplord** [mathiasvr/bluejay#50]
Motors stop when slider reaches 1500

Tried calibrating the esc's via betaflight, moved slider to max and plugged in battery to esc, esc didnt beep but beeps when slider moved to lowest position

**Comment by SquidDerplord** [comment]
The motors spin up correctly and doesn't stop at 1501 when using BLHeli_S firmware

**Comment by mathiasvr** [comment]
Sounds like you enabled bidirectional motor direction in the ESC settings.
