### ISSUE TITLE
PWM firmware version missing

### ISSUE THREAD

**Issue by jesuslg123** [mathiasvr/bluejay#66]
### Describe the issue

I could not see a Pavo Pico ESC PWM version installed due to the lack on information on the ESC title. Read setup usually shows the PWM for each ESC but is not being shown.

![image](https://github.com/mathiasvr/bluejay/assets/7817064/1272e512-6120-4435-918e-44e3ed3e33fa)

I used the production website on Edge browser.
Drone is a Pavo Pico.

Thank you.

### Bluejay version

0.19

### ESC variant

C_X_70

### PWM frequency

Any

### FC firmware

Betaflight 4.3.2

### Motor size

1102

**Comment by stylesuxx** [comment]
This is the wrong repo. I opened an issue here here => https://github.com/stylesuxx/esc-configurator/issues/422

**Comment by jesuslg123** [comment]
Thanks
